# Project: CircleLinkDemo
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = CircleList.o main.o
LINKOBJ  = CircleList.o main.o
LIBS     = -L"E:/ProgramTool/Dev-Cpp/MinGW64/lib32" -L"E:/ProgramTool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"E:/ProgramTool/Dev-Cpp/MinGW64/include" -I"E:/ProgramTool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ProgramTool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/ProgramTool/Dev-Cpp/MinGW64/include" -I"E:/ProgramTool/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/ProgramTool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/ProgramTool/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = CircleLinkDemo.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

CircleList.o: CircleList.c
	$(CC) -c CircleList.c -o CircleList.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
